import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, FileCheck2, ShieldCheck } from "lucide-react";
import { getSiteContent } from "../../../lib/site-content";
import { EnglishShell } from "../en-shell";

export const metadata:Metadata={title:"Medical Equipment Intelligence",description:"Compare medical-equipment categories with procurement, infrastructure, acceptance and lifecycle context.",keywords:["medical equipment comparison","medical equipment specifications","procurement decision support","medical equipment lifecycle"],alternates:{canonical:"/en/products",languages:{"fa-IR":"/products","en":"/en/products","x-default":"/en/products"}},openGraph:{title:"Medical Equipment Intelligence | Clinoro",description:"Equipment categories with procurement, infrastructure, acceptance and lifecycle context.",url:"/en/products",locale:"en_US",type:"website",images:[{url:"/assets/ultrasound.jpg",alt:"Medical equipment intelligence and comparison"}]},twitter:{card:"summary_large_image",title:"Medical Equipment Intelligence | Clinoro",description:"Equipment categories with procurement, infrastructure, acceptance and lifecycle context.",images:["/assets/ultrasound.jpg"]}};
export default async function EnglishProducts(){const content=await getSiteContent();const list={"@context":"https://schema.org","@type":"ItemList",inLanguage:"en",numberOfItems:content.products.length,itemListElement:content.products.map((p,index)=>({"@type":"ListItem",position:index+1,name:p.en,url:`https://clinoromedical.com/en/products/${p.slug}`}))};return <EnglishShell content={content} active="/en/products"><main id="main-content" className="global-products"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(list)}}/><section className="global-inner-hero"><div className="site-wrap"><span>MEDICAL EQUIPMENT INTELLIGENCE</span><h1>Equipment decisions with lifecycle context</h1><p>Each page separates category guidance from verified model evidence and brings infrastructure, acceptance, training and service questions into the buying process.</p><div><ShieldCheck size={18}/> Reference imagery never implies brand representation or availability.</div></div></section><section className="section"><div className="site-wrap global-product-grid">{content.products.map(product=><article key={product.slug}><Link href={`/en/products/${product.slug}`} className="global-product-image"><Image src={product.image} alt={`Reference image for ${product.en}`} fill unoptimized sizes="(max-width:700px) 100vw,33vw"/><span>{product.tag}</span></Link><div><small>{product.procurement.evidenceLevel==="category"?"CATEGORY INTELLIGENCE":product.procurement.evidenceLevel==="model"?"MODEL IDENTIFIED":"VERIFIED MODEL"}</small><h2>{product.en}</h2><p>{product.international.summary}</p><dl><div><dt>Lead time</dt><dd>{product.international.procurement.leadTime}</dd></div><div><dt>Documentation</dt><dd>{product.documents.length?`${product.documents.length} file(s)`:"Requested with final model"}</dd></div></dl><Link href={`/en/products/${product.slug}`}>Open decision profile <ArrowRight size={16}/></Link></div></article>)}</div></section><section className="global-catalog-note"><div className="site-wrap"><FileCheck2/><div><b>Need a model-level comparison?</b><p>Share your intended use, capacity and project timeline. The final comparison is prepared against the exact brand, model and configuration offered.</p></div><Link href="/en/contact">Start an RFQ <ArrowRight size={16}/></Link></div></section></main></EnglishShell>}
