import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2, ClipboardCheck, FileSearch, Gauge, Network, ShieldCheck, Target } from "lucide-react";
import { getSiteContent } from "../../lib/site-content";
import { EnglishShell } from "./en-shell";

export const metadata:Metadata={title:"Medical Equipment Procurement & Lifecycle",description:"Clinoro supports structured medical-equipment selection, procurement, implementation and lifecycle planning.",keywords:["medical equipment procurement","healthcare technology","equipment lifecycle planning","medical equipment RFQ","Clinoro"],alternates:{canonical:"/en",languages:{"fa-IR":"/","en":"/en","x-default":"/en"}},openGraph:{title:"Clinoro | Medical Equipment Procurement & Lifecycle",description:"Structured equipment decisions from requirements to implementation and lifecycle support.",url:"/en",locale:"en_US",type:"website",images:[{url:"/assets/clinoro-hero-prism.webp",alt:"Clinoro medical equipment procurement and lifecycle planning"}]},twitter:{card:"summary_large_image",title:"Clinoro | Medical Equipment Procurement & Lifecycle",description:"Structured equipment decisions from requirements to implementation and lifecycle support.",images:["/assets/clinoro-hero-prism.webp"]}};

export default async function EnglishHome(){const content=await getSiteContent();const i=content.international;const schema={"@context":"https://schema.org","@type":"WebPage",name:"Clinoro Medical Equipment Procurement & Lifecycle",url:"https://clinoromedical.com/en",inLanguage:"en",isPartOf:{"@type":"WebSite",name:"Clinoro",url:"https://clinoromedical.com"}};return <EnglishShell content={content}><main id="main-content" className="global-home"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  <section className="global-hero"><Image src={content.home.heroImage} alt="Medical technology procurement and implementation" fill priority unoptimized sizes="100vw"/><div className="global-hero-shade"/><div className="site-wrap"><span>{i.eyebrow}</span><h1>{i.title}</h1><p>{i.text}</p><div><Link href="/en/products">Explore equipment <ArrowRight size={18}/></Link><Link href="/en/contact">Build an RFQ</Link></div><aside><article><b>Requirements first</b><small>Clinical use, infrastructure and workflow</small></article><article><b>Evidence-aware</b><small>No unverified model or availability claims</small></article><article><b>Lifecycle included</b><small>Training, acceptance, service and TCO</small></article></aside></div></section>
  <section className="global-buyer section"><div className="site-wrap"><header><span>BUYER DECISION SYSTEM</span><h2>{i.buyerTitle}</h2><p>{i.buyerText}</p></header><div><article><Target/><small>01 · DEFINE</small><h3>Clinical requirement</h3><p>Care setting, intended use, capacity, risk and project timeline.</p></article><article><FileSearch/><small>02 · COMPARE</small><h3>Evidence and configuration</h3><p>Model-level specifications, documents, infrastructure and differences.</p></article><article><ClipboardCheck/><small>03 · RFQ</small><h3>Documented decision pack</h3><p>Scope, acceptance, training, service expectations and commercial questions.</p></article></div></div></section>
  <section className="global-featured"><div className="site-wrap"><header><div><span>PROCUREMENT-READY CATEGORIES</span><h2>Start with the clinical pathway</h2></div><Link href="/en/products">View all equipment <ArrowRight size={17}/></Link></header><div>{content.products.slice(0,4).map(product=><Link href={`/en/products/${product.slug}`} key={product.slug}><span><Image src={product.image} alt={`Reference image for ${product.en}`} fill unoptimized sizes="(max-width:700px) 100vw,25vw"/></span><small>{product.tag}</small><h3>{product.en}</h3><p>{product.international.summary}</p><em>{product.procurement.evidenceLevel==="category"?"Category intelligence":"Model intelligence"} <ArrowRight size={14}/></em></Link>)}</div></div></section>
  <section className="global-trust section"><div className="site-wrap"><header><span>DOCUMENTED TRUST</span><h2>{i.trustTitle}</h2><p>{i.trustText}</p></header><div><article><Network/><b>Infrastructure</b><p>Site, utilities, connectivity and implementation dependencies.</p></article><article><CheckCircle2/><b>Acceptance</b><p>Testable handover criteria, records and user training.</p></article><article><Gauge/><b>Lifecycle</b><p>PM, consumables, service response and ownership cost.</p></article><article><ShieldCheck/><b>Evidence boundary</b><p>Commercial commitments exist only in the official project proposal.</p></article></div><Link href="/en/credentials">Review the transparency standard <ArrowRight size={17}/></Link></div></section>
  <section className="global-cta"><div className="site-wrap"><span>START WITH YOUR PROJECT</span><h2>{i.contactTitle}</h2><p>{i.contactText}</p><Link href="/en/contact">Start a structured request <ArrowRight size={18}/></Link></div></section>
  </main></EnglishShell>}
