import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Activity, ArrowLeft, Check, ChevronLeft, ClipboardCheck, Download, FileText, Gauge, GraduationCap, Network, PackageSearch, ShieldCheck, Target, Wrench } from "lucide-react";
import { getSiteContent } from "../../../lib/site-content";
import { PageShell } from "../../components";

type ProductParams={params:Promise<{slug:string}>};

export async function generateMetadata({params}:ProductParams):Promise<Metadata>{
  const {slug}=await params;const content=await getSiteContent();const product=content.products.find(item=>item.slug===slug);
  if(!product)return {title:"محصول پیدا نشد"};
  const title=`${product.fa} | تجهیزات پزشکی`;
  const socialTitle=`${title} | Clinoro`;
  return {title,description:product.summary,alternates:{canonical:`/products/${product.slug}`},openGraph:{title:socialTitle,description:product.summary,url:`/products/${product.slug}`,type:"website",images:[{url:product.image,alt:`تصویر مرجع ${product.fa}`}]},twitter:{card:"summary_large_image",title:socialTitle,description:product.summary,images:[product.image]}};
}

export default async function ProductDetailPage({params}:ProductParams){
  const {slug}=await params;const content=await getSiteContent();const product=content.products.find(item=>item.slug===slug);if(!product)notFound();
  const schema={"@context":"https://schema.org","@type":"Product",name:product.fa,alternateName:product.en,description:product.summary,image:`https://clinoromedical.com${product.image}`,category:product.tag,brand:{"@type":"Brand",name:product.brand},model:product.model,url:`https://clinoromedical.com/products/${product.slug}`,audience:{"@type":"Audience",audienceType:"Hospitals, clinics and healthcare procurement teams"},additionalProperty:product.technicalSpecs.map(spec=>({"@type":"PropertyValue",name:spec.label,value:spec.value})),subjectOf:product.documents.map(document=>({"@type":"DigitalDocument",name:document.title,encodingFormat:document.type,url:document.url}))};
  const crumbs={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"خانه",item:"https://clinoromedical.com/"},{"@type":"ListItem",position:2,name:"محصولات",item:"https://clinoromedical.com/products"},{"@type":"ListItem",position:3,name:product.fa,item:`https://clinoromedical.com/products/${product.slug}`}]};
  const faq={"@context":"https://schema.org","@type":"FAQPage",mainEntity:[{"@type":"Question",name:`پیش از خرید ${product.fa} چه اطلاعاتی باید مشخص شود؟`,acceptedAnswer:{"@type":"Answer",text:`کاربرد موردنظر، ظرفیت، زیرساخت محل، مدل و پیکربندی نهایی، مصرفی‌ها، آموزش و محدوده خدمات باید در پیشنهاد فنی ثبت شوند.`}},{"@type":"Question",name:"آیا مشخصات این صفحه مشخصات قطعی محصول است؟",acceptedAnswer:{"@type":"Answer",text:"خیر. این صفحه گروه محصول را معرفی می‌کند و مشخصات قطعی فقط در دیتاشیت رسمی برند و مدل منتخب تأیید می‌شود."}},{"@type":"Question",name:"چه خدماتی باید همراه پیشنهاد بررسی شود؟",acceptedAnswer:{"@type":"Answer",text:product.services.join("، ")} }]};
  return <PageShell active="/products"><main id="main-content" className="product-detail-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(crumbs)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faq)}}/>
    <section className="product-detail-hero"><div className="product-detail-aura"/><div className="site-wrap product-detail-hero-grid">
      <div className="product-detail-media prism-edge"><Image src={product.image} alt={`تصویر مرجع گروه محصول ${product.fa}`} fill priority unoptimized sizes="(max-width:900px) 100vw,52vw"/><span>REFERENCE IMAGE · {product.imageLicense}</span></div>
      <div className="product-detail-copy glass-panel prism-edge"><div className="breadcrumbs"><Link href="/">خانه</Link><ChevronLeft size={14}/><Link href="/products">محصولات</Link><ChevronLeft size={14}/><span>{product.fa}</span></div><span className="hero-kicker">{product.tag}</span><h1>{product.fa}</h1><small>{product.en}</small><p>{product.summary}</p><dl><div><dt>برند</dt><dd>{product.brand}</dd></div><div><dt>مدل</dt><dd>{product.model}</dd></div><div><dt>وضعیت تأمین</dt><dd>{product.availability}</dd></div></dl><div className="inner-actions"><Link className="button button-primary" href={`/contact?product=${product.slug}`}>درخواست پیشنهاد و دیتاشیت <ArrowLeft size={17}/></Link><Link className="button button-glass" href={`/products?compare=${product.slug}`}>افزودن به مقایسه</Link></div></div>
    </div></section>
    <section className="section product-detail-content"><div className="site-wrap product-detail-layout"><div className="product-detail-main">
      <article className="detail-card glass-panel"><span className="eyebrow">INTENDED USE</span><h2>کاربرد و دامنه انتخاب</h2><p>{product.intendedUse}</p><div className="product-disclaimer"><ShieldCheck size={20}/><p>اطلاعات این صفحه برای معرفی گروه محصول است. مشخصات نهایی، برند، مدل و کاربرد مجاز فقط در پیشنهاد فنی و دیتاشیت رسمی مدل منتخب تأیید می‌شود.</p></div></article>
      <article className="detail-card glass-panel"><span className="eyebrow">TECHNICAL PROFILE</span><h2>مشخصات قابل انتخاب</h2><div className="technical-table">{product.technicalSpecs.map(spec=><div key={`${spec.label}-${spec.value}`}><b>{spec.label}</b><span>{spec.value}</span></div>)}</div></article>
      <article className="detail-card glass-panel product-decision-pack"><span className="eyebrow">PROCUREMENT DECISION PACK</span><h2>بسته تصمیم خرید این گروه محصول</h2><p>پیشنهاد قابل اتکا فقط مشخصات دستگاه نیست؛ این شش محور باید هم‌زمان برای همان مرکز و همان مدل بسته شوند.</p><div className="decision-pack-grid"><article><Target/><b>کاربرد بالینی</b><span>{product.intendedUse}</span></article><article><Network/><b>زیرساخت و اتصال</b><span>فضا، برق، شبکه، تهویه و اتصال سامانه‌ها</span></article><article><PackageSearch/><b>مصرفی و قطعه</b><span>دسترسی، lead time و اقلام ضروری بهره‌برداری</span></article><article><GraduationCap/><b>آموزش</b><span>کاربر، مهندسی پزشکی و سوابق تحویل آموزش</span></article><article><ClipboardCheck/><b>آزمون پذیرش</b><span>معیارهای FAT/SAT یا کنترل تحویل متناسب با تجهیز</span></article><article><Gauge/><b>چرخه عمر</b><span>PM، زمان پاسخ، escalation و هزینه مالکیت</span></article></div></article>
      <article className="detail-card glass-panel"><span className="eyebrow">DOCUMENTS</span><h2>دیتاشیت و مدارک</h2>{product.documents.length?<div className="document-list">{product.documents.map(document=><a href={document.url} target="_blank" rel="noreferrer" key={`${document.title}-${document.url}`}><FileText size={19}/><span><b>{document.title}</b><small>{document.type}</small></span><Download size={17}/></a>)}</div>:<div className="document-empty"><FileText size={24}/><div><b>دیتاشیت پس از انتخاب مدل ارائه می‌شود</b><p>برای جلوگیری از ارائه مشخصات اشتباه، سند رسمی همراه پیشنهاد فنی همان برند و مدل منتخب ارسال خواهد شد.</p></div></div>}</article>
    </div><aside className="product-detail-aside"><article className="detail-card glass-panel"><span className="eyebrow">KEY POINTS</span><h2>ویژگی‌های کلیدی</h2><ul>{product.specs.map(spec=><li key={spec}><Check size={16}/>{spec}</li>)}</ul></article><article className="detail-card glass-panel"><span className="eyebrow">LIFECYCLE SERVICES</span><h2>خدمات همراه</h2><ul>{product.services.map(service=><li key={service}><Wrench size={16}/>{service}</li>)}</ul></article><article className="detail-card glass-panel product-readiness-card"><span className="eyebrow">BEFORE RFQ</span><h2>اطلاعات لازم برای پیشنهاد دقیق</h2><ul><li><Activity size={16}/>نوع مرکز و کاربرد اصلی</li><li><Network size={16}/>زیرساخت و سیستم‌های متصل</li><li><Gauge size={16}/>ظرفیت یا حجم استفاده</li><li><ShieldCheck size={16}/>انتظارات خدمات و آموزش</li></ul><Link href={`/contact?product=${product.slug}`}>تکمیل اطلاعات پروژه <ArrowLeft size={16}/></Link></article><article className="image-credit-card"><small>اعتبار تصویر مرجع</small><a href={product.imageSource} target="_blank" rel="license noreferrer">{product.imageCredit} · {product.imageLicense}</a><p>تصویر صرفاً نماینده گروه محصول است و به معنی عرضه برند نمایش‌داده‌شده نیست.</p></article></aside></div></section>
  </main></PageShell>;
}
